import { NextResponse } from "next/server"

interface Product {
  id: string
  name: string
  description: string
  price: number
  image_url: string
  category?: string
  supplier?: string
  unit?: string
}

// In-memory product data (in production, this would be from a database)
const products: Product[] = [
  {
    id: "146953",
    name: "ProForm Vacuum Former, 220 Volt for international plugs/outlets. Single",
    description: "ProForm Vacuum Former, 220 Volt for international plugs/outlets. Single Chambered, Aluminum Construction, 5 Year Warranty, Made in the USA. Symmetrical heating element provides uniform heat distribution and rotates 180 degree for access. Hexagonal post keeps sliding frame from twisting. Space-saving size - only 13 1/2\" tall. Produces dozens of useful thermoplastic appliances such as mouth-guards, niteguards, TMJ splints, bleaching trays, temporary crown and bridge forms, retainers and more.",
    price: 481.39,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/keystone-industries/proform/media/vacuum-former-9594480.jpg",
    category: "Lab Equipment",
    supplier: "Keystone Industries",
  },
  {
    id: "102175",
    name: "Coltene/Whaledent 6\" (152 mm) Metal Rubber Dam Frame, Single Frame",
    description: "6\" (152 mm) Metal Rubber Dam Frame, Single Frame.",
    price: 36.43,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/coltene-whaledent/coltene-whaledent/media/coltene-hygenic-rubber-dam-frames.jpg",
    category: "Instruments",
    supplier: "Coltene Whaledent",
  },
  {
    id: "102184",
    name: "Miltex Biopsy Punch 3.0 mm, Box of 50 punches",
    description: "Biopsy Punch 3.0 mm, Box of 50 punches.",
    price: 115.53,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/miltex-integra/miltex/media/miltex-biopsy-punch-33-31b-33-32.jpg",
    category: "Instruments",
    supplier: "Miltex",
  },
  {
    id: "102180",
    name: "Miltex Biopsy Punch 2 mm, Box of 50 punches",
    description: "Biopsy Punch 2 mm, Box of 50 punches.",
    price: 124.32,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/miltex-integra/miltex/media/dn1uyf.jpg",
    category: "Instruments",
    supplier: "Miltex",
  },
  {
    id: "87660",
    name: "Big Boy Press #38B Heavy Duty Two Flask Press manufactured of malleable/ductile",
    description: "Big Boy Press #38B Heavy Duty Two Flask Press manufactured of malleable/ductile cast iron. Features are the same as 38 Press, except this unit is designed to accommodate two flasks simultaneously. Shipping Weigt: 24 lbs (10.9 Kg), Dimensions: 10\" long x 4 1/2\" wide x 10\" high (25cm x 11cm x 25cm).",
    price: 378.09,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/handler-manufacturing/big-boy/media/Big-Boy-Press-2flask-38B.jpg",
    category: "Lab Equipment",
    supplier: "Handler Manufacturing",
  },
  {
    id: "102187",
    name: "Miltex Biopsy Punch 5.0 mm, Box of 50 punches",
    description: "Biopsy Punch 5.0 mm, Box of 50 punches.",
    price: 115.77,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/miltex-integra/miltex/media/miltex-biopsy-punch-33-33-v1.jpg",
    category: "Instruments",
    supplier: "Miltex",
  },
  {
    id: "106267",
    name: "GC Initial MC (Metal-Ceramic) Paste Opaque Refill, Shade OA3.5, 3gm jar",
    description: "GC Initial MC (Metal-Ceramic) Paste Opaque Refill, Shade OA3.5, 3gm jar.",
    price: 28.39,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/gc-america/gc-initial-mc/media/gc-initial-mc-opaque-3-gram-870003.jpg",
    category: "Materials",
    supplier: "GC America",
  },
  {
    id: "102191",
    name: "Accolade PV Try-In Paste Refill, Light Shade, Single 3 gram syringe",
    description: "Accolade PV Try-In Paste Refill, Light Shade, Single 3 gram syringe.",
    price: 59.45,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/danville-materials/accolade-pv/media/danville-accolade-pv-refill.jpg",
    category: "Materials",
    supplier: "Danville Materials",
  },
  {
    id: "102188",
    name: "Miltex Biopsy Punch 6.0 mm, Box of 50 punches",
    description: "Biopsy Punch 6.0 mm, Box of 50 punches.",
    price: 114.22,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/miltex-integra/miltex/media/miltex-biopsy-punch-33-36-v1.jpg",
    category: "Instruments",
    supplier: "Miltex",
  },
  {
    id: "144518",
    name: "Osung Cortical bone scraper. Manual bone harvesting device which is most",
    description: "Cortical bone scraper. Manual bone harvesting device which is most advanced product for the application. It has 360 degree rotating blade which allows four sharp edges for maximum cutting efficiency. Ready to use comes in sterile pouch. Single bone scrapers.",
    price: 45.95,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/osung/osung/media/osung-bone-scraper-BSF.jpg",
    category: "Instruments",
    supplier: "Osung",
  },
  {
    id: "172322",
    name: "ONE CURE O-Star Wide-Spectrum Curing Light with Charging Base, 1/Pk",
    description: "ONE CURE O-Star Wide-Spectrum Curing Light with Charging Base, 1/Pk. Light intensity up to 3000 MW/CM2 with built-in light meter. 385-515nm wavelength range. 7 modes: Normal, High, Turbo, Ortho, Soft, Pulse, and Check. 360 rotatable head, easy to illuminate all angles in the mouth. Full metal body, ergonomically-streamlined design, 108g main unit, light but strong, anti shock and durable. Uniform beam, strong penetrability, less light loss. Equipped with OLED screen. 1 year warranty.",
    price: 463.97,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/guilin-woodpecker-medical-instrument-co/one-cure/media/onecure-ostarwidespectrumcuringlight-o-star-v1.jpg",
    category: "Equipment",
    supplier: "Guilin Woodpecker",
  },
  {
    id: "128719",
    name: "ClearView Single-Use Nasal Hoods - Adult, Fresh Mint 12/Box",
    description: "Single-Use Nasal Hoods - Adult, Fresh Mint 12/Box. Individually Wrapped. Clear outer hood shows condensation when patients are breathing through their nose. Hood-in-hood design minimizes ambient nitrous oxide release. Low-profile design expands the clinical field of view. Latex-free.",
    price: 96.89,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/crosstex-accutron/clearview/media/clearview-single-use-nasal-hood-12-pack-33035-16-mint.jpg",
    category: "Disposables",
    supplier: "Crosstex Accutron",
  },
  {
    id: "54838",
    name: "Scalex 830 Ultrasonic Scaler Unit with 30K Tip. System includes handpiece",
    description: "Scalex 830 Ultrasonic Scaler Unit with 30K Tip. System includes handpiece with 8 ft. cord, one autoclavable 30kHz insert, foot pedal control with 6 ft. cord, 6 ft. water supply line with 1/4\" male quick-connector and in-line T-fitting, and DC power supply. Automatic tuning activates inserts in an elliptical pattern for feather-touch removal of stains and calculus under all loading conditions - no power loss under pressure. Tips are autoclavable.",
    price: 433.04,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/dentamerica/scalex-830/media/DentAmerica-Scalex-830-ultrasonic-scaler-830.jpg",
    category: "Equipment",
    supplier: "DentAmerica",
  },
  {
    id: "186329",
    name: "Surcam S-Type Implant, 5 x 16 mm, 2.43 mm Internal Hex, 1/Pk. Includes",
    description: "Surcam S-Type Implant, 5 x 16 mm, 2.43 mm Internal Hex, 1/Pk. Includes abutment screw and implant driver. Offers self-drilling and self-tapping design for high primary stability, even in soft bone, enabling minimal bone loss and reduced trauma. Ideal for immediate loading, features SLA-treated surface, anchoring apex, conical threads, and micro-threaded body.",
    price: 90,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/surcam/surcam/media/mfr-surcam-dentalimplants-s-type.jpg",
    category: "Implants",
    supplier: "Surcam",
  },
  {
    id: "102196",
    name: "Accolade SRO, Shade A2, Single 5 gram syringe",
    description: "Accolade SRO, Shade A2, Single 5 gram syringe.",
    price: 35.9,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/danville-materials/accolade-sro/media/mfr-danville-materials-accolade-sro-z2-radiopaque-flowable-resin-91387.jpg",
    category: "Materials",
    supplier: "Danville Materials",
  },
  {
    id: "106430",
    name: "GC Initial MC Initial MC (Metal-Ceramic) Ceramic Restoration System, Basic Set",
    description: "Initial MC (Metal-Ceramic) Ceramic Restoration System, Basic Set Includes: 16 Paste Opaque syringes, 16 Dentin, 4 Enamel, 3 INside Basic, Clear Fluorescence, 2 Translucent, Glaze, INcisio, 25ml Glaze Liquid, and 50ml Modeling Liquid. Shade Guides not included.",
    price: 1318.35,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/gc-america/gc-initial-mc/media/gc-america-initial-ceramic-system-870001.jpg",
    category: "Materials",
    supplier: "GC America",
  },
  {
    id: "160685",
    name: "SOL Disposable Laser Tips, 400um-4mm, 25/Pk",
    description: "SOL Disposable Laser Tips, 400um, 4mm, 25/Pk. Single-use, disposable tips are pre-scored and pre-stripped to virtually eliminate set-up time.",
    price: 207.95,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/denmat/sol/media/denmat-sol-laser-parts-n-accessories-033980028-0.jpg",
    category: "Disposables",
    supplier: "DenMat",
  },
  {
    id: "102201",
    name: "TPC Advanced Technology Lubrication Fluid for H6000 or H6005 Handpiece Cleaning",
    description: "Lubrication Fluid for H6000 or H6005 Handpiece Cleaning and Lubrication System.",
    price: 69.99,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/dental/common/misc/not-found.png",
    category: "Maintenance",
    supplier: "TPC Advanced Technology",
  },
  {
    id: "102202",
    name: "TPC Advanced Technology Mist Filters for H6000 or H6005 Handpiece Cleaning",
    description: "Mist Filters for H6000 or H6005 Handpiece Cleaning and Lubrication System, Package of 12 filters.",
    price: 28,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/dental/common/misc/not-found.png",
    category: "Maintenance",
    supplier: "TPC Advanced Technology",
  },
  {
    id: "74812",
    name: "Pindex Long (20 mm) Pins and Plastic Sleeves, Bulk Pack of 1000 Pins and 1000",
    description: "Pindex Long (20 mm) Pins and Plastic Sleeves, Bulk Pack of 1000 Pins and 1000 Sleeves.",
    price: 125.95,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/coltene-whaledent/pindex/media/coltene-pindex-system-px200.jpg",
    category: "Lab Equipment",
    supplier: "Coltene Whaledent",
  },
  {
    id: "102208",
    name: "Air Polishing System, EZ Nozzle for P555 1/Pk. Fully autoclavable up to 134",
    description: "EZ Nozzle for P555 Air Polishing System, 1/Pk. Fully autoclavable up to 134 C/273 F. Carefully designed length, angle and curve of nozzle for applications to both anterior and posterior teeth.",
    price: 59.9,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/tpc/air-polishing-system/media/ez-nozzle-P660.jpg",
    category: "Instruments",
    supplier: "TPC",
  },
  {
    id: "102213",
    name: "Quala 25 Gauge Long 1-3/8\" Dental Needles, Red, Pre-threaded plastic hub, Bevel",
    description: "25 Gauge Long 1-3/8\" Dental Needles, Red, Pre-threaded plastic hub, Bevel indicator on the hub for quick orientation of needle, color-coded cap. Box of 100 needles.",
    price: 24.76,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/quala/quala/media/house-25g-long-red-26-DP40825-HB-v2.jpg",
    category: "Disposables",
    supplier: "Quala",
  },
  {
    id: "102207",
    name: "Air Polishing System, Jet Polishing Prophy Powder, 130 gram. refreshing lemon",
    description: "Jet Polishing Prophy Powder, 130 gram. For Air Polishing System, refreshing lemon scent.",
    price: 33,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/dental/common/misc/not-found.png",
    category: "Materials",
    supplier: "TPC",
  },
  {
    id: "148698",
    name: "Premier Heidbrink 13-14 root tip pick with Light Touch Handle, single instrument",
    description: "Heidbrink 13-14 root tip pick with Light Touch Handle, single instrument.",
    price: 57.04,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/premier/premier/media/heindbrink13-14-1003396.jpg",
    category: "Instruments",
    supplier: "Premier",
  },
  {
    id: "52218",
    name: "After Five Swivel Direct Flow #10 Swivel Direct Flow 30 kHz Universal",
    description: "#10 Swivel Direct Flow 30 kHz Universal Ultrasonic Insert, Single Insert. Compatible Generator: Biosonic, Cavitron, Integra, Select, Swerv3. Lavender grip color.",
    price: 206.48,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/hu-friedy/after-five-swivel-direct-flow/media/hu-friedy-10-universal-swivel-direct-flow-insert-ui25d10-v1.jpg",
    category: "Instruments",
    supplier: "Hu-Friedy",
  },
  {
    id: "143293",
    name: "EverEdge 2.0 #H6/7 hygienist scaler with #8 ResinEight Colors handle",
    description: "#H6/7 hygienist scaler with #8 ResinEight Colors handle.",
    price: 58.89,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/dental/common/misc/not-found.png",
    category: "Instruments",
    supplier: "EverEdge",
  },
  {
    id: "102215",
    name: "Quala 30 Gauge X-Short 3/8\" Dental Needles, Purple, Pre-threaded plastic hub",
    description: "30 Gauge X-Short 3/8\" Dental Needles, Purple, Pre-threaded plastic hub, Bevel indicator on the hub for quick orientation of needle, color-coded cap. Box of 100 needles.",
    price: 15.41,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/quala/quala/media/purple_plastic_hub_needles-v1.jpg",
    category: "Disposables",
    supplier: "Quala",
  },
  {
    id: "102217",
    name: "Quala 27 Gauge Short 1\" Dental Needles, Orange, Pre-threaded plastic hub, Bevel",
    description: "27 Gauge Short 1\" Dental Needles, Orange, Pre-threaded plastic hub, Bevel indicator on the hub for quick orientation of needle, color-coded cap. Box of 100 needles.",
    price: 16.25,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/quala/quala/media/40ga-orange-v1.jpg",
    category: "Disposables",
    supplier: "Quala",
  },
  {
    id: "102216",
    name: "Quala 25 Gauge Short 1\" Dental Needles, Pink, Pre-threaded plastic hub, Bevel",
    description: "25 Gauge Short 1\" Dental Needles, Pink, Pre-threaded plastic hub, Bevel indicator on the hub for quick orientation of needle, color-coded cap. Box of 100 needles.",
    price: 24.76,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/quala/quala/media/house-27g-sterile-disposable-needle.jpg",
    category: "Disposables",
    supplier: "Quala",
  },
  {
    id: "87189",
    name: "Keystone Deluxe Articulator, Removable Pins, Interchangeable Mounts, Full Range",
    description: "Deluxe Articulator, Removable Pins, Interchangeable Mounts, Full Range of Movements Including Lateral Excursions, Baked Black Teflon Coating.",
    price: 46.67,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/keystone-industries/keystone/media/keystone-deluxe-articulator-1050095.jpg",
    category: "Lab Equipment",
    supplier: "Keystone Industries",
  },
  {
    id: "93368",
    name: "Personal Inhaler Plus Disposable Nasal Hood - Medium, Variety Pack #1: Orange",
    description: "Personal Inhaler Plus Disposable Nasal Hood - Medium, Variety Pack #1: Orange, Strawberry, Bubble Gum 24/Pack. Single use only, Individually wrapped. Provides cross-infection protection, convenience and flavor. Increase patient satisfaction and referrals. Speed up production by not waiting for a clean hood. Not made with natural rubber latex.",
    price: 124.35,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/crosstex-accutron/personal-inhaler-plus/media/mfr-accutron-personal-inhaler-nasal-hood-variety-pack-33015-1.jpg",
    category: "Disposables",
    supplier: "Crosstex Accutron",
  },
  {
    id: "177616",
    name: "Cavitron FSI Slimline Ultrasonic FITGRIP Insert, 30K Focused Spray Slimline 1000, 1/Pk",
    description: "Cavitron FSI Slimline Ultrasonic FITGRIP Insert, 30K Focused Spray Slimline 1000, 1/Pk. For light to moderate calculus deposits. 30% thinner to enhance subgingival access.",
    price: 220.49,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/dentsply-professional/cavitron-fsi-slimline/media/mfr-dentsplysirona-cavitron-ultrasonicslimline-fitgrip-insert30k-fitgripfocusedsprayslimline1000-1pk-82008.jpg",
    category: "Instruments",
    supplier: "Dentsply Professional",
  },
  {
    id: "174268",
    name: "Woodpecker iLED II Wide Spectrum Curing Light with Magnetic Point Cure Lens",
    description: "Woodpecker iLED II Wide Spectrum Curing Light with Magnetic Point Cure Lens. 3 modes with up to 3000 mw,cm2 light intensity,a 1mm light guide, and cures 2mm or resin in 1 second. Includes a magnetic point cure lens for tack curing. 3 mode time settings: Turbo - 1s,3s; High - 3s,5s; Standard - 5s, 10s, 15s, 20s. 1 Year warranty.",
    price: 177.9,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/guilin-woodpecker-medical-instrument-co/woodpecker/media/woodpecker-curing-light-iled-ii.jpg",
    category: "Equipment",
    supplier: "Guilin Woodpecker",
  },
  {
    id: "102264",
    name: "seT Capsules A1. Self etching, Self Adhesive Resin Cement, Self-Cure",
    description: "seT - Capsules A1. Self etching, Self Adhesive Resin Cement, Self-Cure and Light-Cure, Superior Fluoride Release, Package of 50 - 0.14 ml capsules.",
    price: 383.23,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/sdi/set/media/sdi-set-resin-cement-capsules.jpg",
    category: "Materials",
    supplier: "SDI",
  },
  {
    id: "17422",
    name: "Cavitron FSI Slimline Focused Spray Ultrasonic Insert - 25K FSI-SLI 10S, 1/Pk",
    description: "Cavitron FSI Slimline Focused Spray Ultrasonic Insert - 25K FSI-SLI 10S, 1/Pk. Light Green, Tip Orientation: Straight. Power Level: Low-Medium. Water Delivery: Through-Tip.",
    price: 159.46,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/dentsply-professional/cavitron-fsi-slimline/media/cavitron-FSI-Slimline-25k-insert-straight-80392.jpg",
    category: "Instruments",
    supplier: "Dentsply Professional",
  },
  {
    id: "102296",
    name: "Coe-Rect Powder. Self-Curing Hard Denture Liner and Repair, Powder: 6 oz",
    description: "Coe-Rect - Powder. Self-Curing Hard Denture Liner and Repair, Powder: 6 oz. Powder only.",
    price: 140.4,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/dental/common/misc/not-found.png",
    category: "Materials",
    supplier: "Coe",
  },
  {
    id: "102283",
    name: "SS White FG #245 Short Shank Amalgam Preparation Carbide Bur, clinic pack",
    description: "FG #245 Short Shank Amalgam Preparation Carbide Bur, clinic pack of 100 burs.",
    price: 199.99,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/ss-white/ss-white/media/fg-245-short-shank-amalgam-preparation-carbide-bur-13243.jpg",
    category: "Instruments",
    supplier: "SS White",
  },
  {
    id: "52558",
    name: "MicroEtcher IIA Sandblaster, Fully Autoclavable. Contains: IIA, 60/260 Nozzle",
    description: "Microetcher IIA Sandblaster, Fully Autoclavable. Contains: Microetcher IIA, 60/260 Nozzle, 10 feet air line, 2 abrasive jars and instruction.",
    price: 386.31,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/danville-materials/microetcher/media/danville-microetcher-iia-22005-01.jpg",
    category: "Equipment",
    supplier: "Danville Materials",
  },
  {
    id: "102312",
    name: "Sure-Check 12\" x 18\" Sterilization Pouch 100/Bx. Self-Sealing with Built-In",
    description: "12\" x 18\" Sterilization Pouch 100/Bx. Self-Sealing with Built-In internal/external steam sterilization indicators, verifying proper time, temperature and presence of steam.",
    price: 53.67,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/crosstex/sure-check/media/crosstex-sure-check-sterilization-pouches-scx2.jpg",
    category: "Disposables",
    supplier: "Crosstex",
  },
  {
    id: "148894",
    name: "V35 Electric **Foot Control Only** for use with V35 Console, 120V AC, single",
    description: "**Foot Control Only** for use with V35 Console, 120V AC, single foot control only. Hand piece and console sold separately.",
    price: 87.29,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/buffalo-dental/v35-electric-lab-handpiece-system/media/buffalo-dental-v35-electric-system-foot-control-37430.jpg",
    category: "Equipment",
    supplier: "Buffalo Dental",
  },
  {
    id: "1023",
    name: "3M ESPE #3 Upper Right 1st Molar Gold Anodized Temporary Crown Form, Box of 5",
    description: "#3 Upper Right 1st Molar Gold Anodized Temporary Crown Form, Box of 5 Crown Forms.",
    price: 39.99,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/3m-espe/3m-espe/media/3m_espe_gold_anodized_crown_5_pk.jpg",
    category: "Materials",
    supplier: "3M ESPE",
  },
  {
    id: "121310",
    name: "Keystone Laboratory Pumice Powder, Coarse 0-3/4, 50lb. Bottle",
    description: "Laboratory Pumice Powder, Coarse 0-3/4, 50lb. Bottle.",
    price: 73.44,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/keystone-industries/keystone/media/keystone-laboratory-pumice-flour.jpg",
    category: "Materials",
    supplier: "Keystone Industries",
  },
  {
    id: "102316",
    name: "Sure-Check 3.50\" x 5.25\" Sterilization Pouch 200/Bx. Self-Sealing with Built-In",
    description: "3.50\" x 5.25\" Sterilization Pouch 200/Bx. Self-Sealing with Built-In internal/external steam sterilization indicators, verifying proper time, temperature and presence of steam.",
    price: 15.57,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/crosstex/sure-check/media/crosstex-sure-check-sterilization-pouches-scx2.jpg",
    category: "Disposables",
    supplier: "Crosstex",
  },
  {
    id: "102315",
    name: "Sure-Check 3.50\" x 9\" Sterilization Pouch 200/Bx. Self-Sealing with Built-In",
    description: "3.50\" x 9\" Sterilization Pouch 200/Bx. Self-Sealing with Built-In internal/external steam sterilization indicators, verifying proper time, temperature and presence of steam.",
    price: 18.25,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/crosstex/sure-check/media/crosstex-sure-check-sterilization-pouches-scx2.jpg",
    category: "Disposables",
    supplier: "Crosstex",
  },
  {
    id: "102318",
    name: "Nordent 20 Instrument Sterilization Cassette, Raspberry, Stainless Steel",
    description: "20 Instrument Sterilization Cassette, Raspberry, Stainless Steel, Easy-open, Side Spring Latches and Flow-through Design, 8\"W x 11\"L x 1.25\"H.",
    price: 162.86,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/nordent/nordent/media/nordent-large-cassette-20-instrument-c3-20n.jpg",
    category: "Instruments",
    supplier: "Nordent",
  },
  {
    id: "102313",
    name: "Sure-Check 7.50\" x 13\" Sterilization Pouch 200/Bx. Self-Sealing with Built-In",
    description: "7.50\" x 13\" Sterilization Pouch 200/Bx. Self-Sealing with Built-In internal/external steam sterilization indicators, verifying proper time, temperature and presence of steam.",
    price: 42.65,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/crosstex/sure-check/media/crosstex-sure-check-sterilization-pouches-scx2.jpg",
    category: "Disposables",
    supplier: "Crosstex",
  },
  {
    id: "120676",
    name: "ProForm Tri-Color Mouthguard Laminate - Red/White/Black, 12/Box. 5\" x 5\" .160\"",
    description: "Tri-Color Mouthguard Laminate - Red/White/Black, 12/Box. 5\" x 5\" .160\" (4mm) Two Layer Vacuum Forming EVA Material.",
    price: 93.65,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/keystone-industries/proform/media/keystone-proform-tri-color-mouthguard-laminate.jpg",
    category: "Materials",
    supplier: "Keystone Industries",
  },
  {
    id: "102368",
    name: "Colorvue Probe Kit, UNC12 Markings 1-2-3-4-5-6-7-8-9-10-11-12, Package of 7",
    description: "Colorvue Probe Kit, UNC12 Markings 1-2-3-4-5-6-7-8-9-10-11-12, Package of 7 tips and 1 handle.",
    price: 96.71,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/hu-friedy/colorvue/media/hu-friedy-kit-unc12-pcvnckit.jpg",
    category: "Instruments",
    supplier: "Hu-Friedy",
  },
  {
    id: "102371",
    name: "Colorvue Replacement Tips for Williams Probe, Markings 1-2-3-5-7-8-9-10",
    description: "Replacement Tips for Williams Colorvue Probe, Markings 1-2-3-5-7-8-9-10, Package of 12 Replacement Tips.",
    price: 127.67,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/hu-friedy/colorvue/media/hu-friedy-williams-tips-pcvwpt.jpg",
    category: "Instruments",
    supplier: "Hu-Friedy",
  },
  {
    id: "102367",
    name: "Colorvue Replacement Tips for #11 Probe, Markings 3-6-8-11, Package of 12",
    description: "Replacement Tips for #11 Colorvue Probe, Markings 3-6-8-11, Package of 12 Replacement Tips.",
    price: 127.67,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/hu-friedy/colorvue/media/hu-friedy-11-tip-pcv11pt.jpg",
    category: "Instruments",
    supplier: "Hu-Friedy",
  },
  {
    id: "118356",
    name: "Quick-Clean 3-Way Air/Water Syringe, Standard, with 1 Tip. Quick-Change tip",
    description: "Quick-Clean 3-Way Air/Water Syringe, Standard, with 1 Tip. Quick-Change tip disconnect. Uses standard autoclavable tips or disposable tips. Single air/water syringe, no tubing.",
    price: 48.88,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/dci-international/quick-clean/media/standard_metal_air_water_syringe_3430.jpg",
    category: "Instruments",
    supplier: "DCI International",
  },
  {
    id: "102387",
    name: "Slimline Illuminator, Steel construction with a white enamel finish, Desk",
    description: "Slimline Illuminator, Steel construction with a white enamel finish, Desk or Wall Mount. Viewing area: 4.75\" x 13.74\", Total Dimensions: 6.5\" x 15.25\" x 2.5\". Complete with bulbs, 6-ft cord, and keyholes in back for wall mount.",
    price: 114.95,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/flow-dental/slimline/media/flow-xray-slimline-illuminator-21730.jpg",
    category: "Equipment",
    supplier: "Flow Dental",
  },
  {
    id: "102389",
    name: "Kopy Kat 6\"x12\" Duplicator for Intra-Oral & Extra-Oral Films up to 6\"x12\"",
    description: "6\"x12\" Duplicator for Intra-Oral & Extra-Oral Films up to 6\"x12\", Enamel Finish.",
    price: 599.59,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/flow-dental/kopy-kat/media/flow-x-ray-kopy-kat-21520.jpg",
    category: "Equipment",
    supplier: "Flow Dental",
  },
  {
    id: "133186",
    name: "DTE D5 LED Ultrasonic Scaler, 28kHz-30kHz, 1/Pk",
    description: "DTE D5 LED Ultrasonic Scaler, 28kHz-30kHz, 1/Pk. Compact and powerful Perio and Endo Scaler with one piece detachable autoclavable LED light scaler handpiece. Accessories compatible with Satelec type scaler. Includes 6 tips (ED1, GD1, GD2, GD3, GD4, PD1) one each of Endo Wrench and Torque Wrench. This unit does NOT include the Water Supply or Quick Connector.",
    price: 189.99,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/woodpecker/woodpecker/media/woodpecker-dte-D5-LED.jpg",
    category: "Equipment",
    supplier: "Woodpecker",
  },
  {
    id: "1024",
    name: "3M ESPE #5 Upper Right 1st Molar Gold Anodized Temporary Crown Form, Box of 5",
    description: "#5 Upper Right 1st Molar Gold Anodized Temporary Crown Form, Box of 5 Crown Forms.",
    price: 52.35,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/3m-espe/3m-espe/media/3m_espe_gold_anodized_crown_5_pk.jpg",
    category: "Materials",
    supplier: "3M ESPE",
  },
  {
    id: "10242",
    name: "Bosworth Set of 8 - Edentulous Perforated Full-Arch Stainless Steel Impression",
    description: "Set of 8 - Edentulous Perforated Full-Arch Stainless Steel Impression Trays (#1, #2, #3, #4 Upper and #5, #6, #7, #8 Lower).",
    price: 130.26,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/keystone-industries-bosworth/bosworth/media/stainless-steel-impression-tray-perforated-0921180.jpg",
    category: "Instruments",
    supplier: "Bosworth",
  },
  {
    id: "102418",
    name: "Slix #W3, Double End Composite Manipulation Instrument, Innovative non-stick",
    description: "Slix #W3, Double End Composite Manipulation Instrument, Innovative non-stick coating, Big Easy Handle, Autoclavable. (Do not use iodophors or phenols), Single instrument.",
    price: 49.65,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/premier/slix/media/premier-slix-w3-05705.jpg",
    category: "Instruments",
    supplier: "Premier",
  },
  {
    id: "155725",
    name: "P5 Newtron Satelec scaler tip #1S, slim, 1/Pk. Developed for supra",
    description: "Satelec scaler tip #1S, slim, 1/Pk. Developed for supra and sub-gingival scaling. The lateral edges make it suitable for scaling the interproximal spaces. Finer and longer than tip #1, it is also powerful & robust.",
    price: 56.37,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/acteon-satelec/p5-newtron/media/Satelec-scaler-tip-1S--F00245.jpg",
    category: "Instruments",
    supplier: "Acteon Satelec",
  },
  {
    id: "10252",
    name: "Bosworth Set of 8 - Edentulous Solid Full-Arch Stainless Steel Impression Trays",
    description: "Set of 8 - Edentulous Solid Full-Arch Stainless Steel Impression Trays (#1, #2, #3, #4 Upper and #5, #6, #7, #8 Lower).",
    price: 158.32,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/bosworth/bosworth/media/bosworth-stainless-steel-impression-tray-set-of-10.jpg",
    category: "Instruments",
    supplier: "Bosworth",
  },
  {
    id: "102438",
    name: "Flow X-Ray Adult (24\" x 27\") X-Ray Lead-Free Panoramic Apron without Collar",
    description: "Adult (24\" x 27\") X-Ray Lead-Free Panoramic Apron without Collar - BIG BLUE PAW PRINT, 0.25mm Lead Equiv, Vinyl Facing and Tear Resistant Cling Back. *Special Order Item, allow up to 10 days for delivery. Non-Returnable",
    price: 438.7,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/flow-dental/flow-x-ray/media/flow-x-ray-panoramic-apron.jpg",
    category: "Safety",
    supplier: "Flow Dental",
  },
  {
    id: "17791",
    name: "Steri-Mate Detachable Sterilizable Handpiece for use with Model 3000",
    description: "Steri-Mate Detachable Sterilizable Handpiece for use with Model 3000 and Cavitron SPS Ultrasonic Scaler, 3-Pack.",
    price: 947.14,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/dentsply-professional/steri-mate/media/dentsply-cavitronsteri-mate-detachablesterilizablehandpiece-black-3pk-78703.jpg",
    category: "Instruments",
    supplier: "Dentsply Professional",
  },
  {
    id: "176658",
    name: "House Brand Air/Water Syringe Tips, Stainless Steel, Quick Change style 10/Pk",
    description: "Air/Water Syringe Tips, Stainless Steel, Quick Change style 10/Pk.",
    price: 4.98,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/house-brand/house-brand/media/quickchange-air-water-syringe-tips-10pk.jpg",
    category: "Disposables",
    supplier: "House Brand",
  },
  {
    id: "106976",
    name: "House Brand X-Ray apron hanger",
    description: "X-Ray apron hanger",
    price: 25.1,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/dental/common/misc/not-found.png",
    category: "Accessories",
    supplier: "House Brand",
  },
  {
    id: "102700",
    name: "Alpen FG #839.014 Fine Grit, End Cutting Diamond Bur. Package of 5 Burs",
    description: "FG #839.014 Fine Grit, End Cutting Diamond Bur. Package of 5 Burs.",
    price: 51.8,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/coltene-whaledent/alpen/media/alpen-diamond-burs-end-cutting-839.14-v1.jpg",
    category: "Instruments",
    supplier: "Coltene Whaledent",
  },
  {
    id: "1026",
    name: "Unitek #6 lower right 2nd bicuspid stainless steel crown form, box of 5 crown",
    description: "#6 lower right 2nd bicuspid stainless steel crown form, box of 5 crown forms.",
    price: 39.99,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/3m-espe/unitek/media/3M_Unitek_crowns_5.jpg",
    category: "Materials",
    supplier: "Unitek",
  },
  {
    id: "175146",
    name: "Woodpecker US-II LED Ultrasonic Piezo Bone Cutter. Complete set including Main",
    description: "Woodpecker US-II LED Ultrasonic Piezo Bone Cutter. Complete set including Main Unit with accessories, 2x LED hand pieces, and 14 cutting tips (one each: US1, US2, US3, US4, US5, US1L, US1R, UL1, UL2, UL3, UL4, UL5, UI1, UC1). Best used in Osteotomy, Extractions, Sinus lifts, Implant preparations. 2 year warranty on main unit and 1 year on handpiece (not including customer damages). Free repairs for issues covered by warranty. **No returns if it box has been opened.",
    price: 4000,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/guilin-woodpecker-medical-instrument-co/woodpecker/media/woodpecker-ultra-surgery-bone-cutter-us-ii-led.jpg",
    category: "Equipment",
    supplier: "Guilin Woodpecker",
  },
  {
    id: "10274",
    name: "Comfortcaine Mint flavored, Topical Anesthetic Gel (Benzocaine 20%), 1 oz. Jar",
    description: "Comfortcaine - Mint flavored, Topical Anesthetic Gel (Benzocaine 20%), 1 oz. Jar. #16607",
    price: 13.95,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/bosworth/comfortcaine/media/bosworth-comfortcaine-topical-anesthetic-gel.jpg",
    category: "Medication",
    supplier: "Bosworth",
  },
  {
    id: "10276",
    name: "Copaliner Varnish - Chloroform-Free, 0.5 oz. Bottle. #0921526 *HAZARDOUS",
    description: "Copaliner Varnish - Chloroform-Free, 0.5 oz. Bottle. #0921526 *HAZARDOUS MATERIALS",
    price: 16.85,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/bosworth/copaliner/media/bosworth-copaliner-cavity-varnish-sealant.jpg",
    category: "Materials",
    supplier: "Bosworth",
  },
  {
    id: "10275",
    name: "Copaliner Cavity Varnish and Thinner / Solvent, Complete Kit: 1/2 oz. each",
    description: "Cavity Varnish and Thinner / Solvent, Complete Kit: 1/2 oz. each Varnish and Solvent. *HAZARDOUS MATERIALS",
    price: 18.81,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/bosworth/copaliner/media/bosworth-copaliner-cavity-varnish-sealant.jpg",
    category: "Materials",
    supplier: "Bosworth",
  },
  {
    id: "164021",
    name: "House Brand Gasket Kit for Midmark M11 and M11D. Includes: 1 Door Gasket, 1 Dam",
    description: "Gasket Kit for Midmark M11 and M11D. Includes: 1 Door Gasket, 1 Dam Gasket, and 1 Hoop. OEM #002-0504-00, #057-0790-00.",
    price: 62.33,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/house-brand/midmark-type/media/door-dam-gasket-with-hoop-kit-2195.jpg",
    category: "Maintenance",
    supplier: "House Brand",
  },
  {
    id: "102850",
    name: "Alpen FG #859.010 Extra Fine Grit, Flame Shaped Diamond Bur. Package of 5 Burs",
    description: "FG #859.010 Extra Fine Grit, Flame Shaped Diamond Bur. Package of 5 Burs.",
    price: 42,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/coltene-whaledent/alpen/media/alpen-diamond-burs-flame-859.jpg",
    category: "Instruments",
    supplier: "Coltene Whaledent",
  },
  {
    id: "102944",
    name: "Alpen FG #879.012 Coarse Grit, Beveled Cylinder Diamond Bur. Package of 5 Burs",
    description: "FG #879.012 Coarse Grit, Beveled Cylinder Diamond Bur. Package of 5 Burs.",
    price: 42,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/coltene-whaledent/alpen/media/alpen-diamond-bur-beveled-cylinder-879.jpg",
    category: "Instruments",
    supplier: "Coltene Whaledent",
  },
  {
    id: "149130",
    name: "Zoll Medical Replacement Trainer AC Adapter",
    description: "Replacement Trainer AC Adapter.",
    price: 86.12,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/dental/common/misc/not-found.png",
    category: "Accessories",
    supplier: "Zoll Medical",
  },
  {
    id: "179575",
    name: "Enbio S Class B Autoclave Steam Sterilizer with 3 Programs",
    description: "Enbio S Class B Autoclave Steam Sterilizer with 3 Programs. Sterilizes and fully dries in 15 minutes at 273 degrees F. Accommodates up to 8 packages, and features load space of 11\" x 7.1\" x 1.4\". Compact design with external dimensions 22\" x 9.8\" x 6.3\". Can run up to 1000 processes on 1 liter of demineralized water. All process data is automatically written to a USB disk. 6 times smaller and 3 times lighter than a regular vacuum autoclave, weighing 33 Lbs.",
    price: 3389,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/enbio/enbio-s/media/mfr-enbio-s-classb-autoclavesteamsterilizer-with3programs-1-8-1133460.jpg",
    category: "Equipment",
    supplier: "Enbio",
  },
  {
    id: "140783",
    name: "DCI Dental O-Ring Kit. Includes 360 rings, 12 each of 30 common sizes",
    description: "Dental O-Ring Kit. Includes 360 rings, 12 each of 30 common sizes, for replacement in evacuators, A-W syringes and equipment. Divided plastic box contains handy chart for reference.",
    price: 80.38,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/dci/dci/media/dci-o-ring-kit-8067.jpg",
    category: "Maintenance",
    supplier: "DCI",
  },
  {
    id: "10298",
    name: "Fastray Standard Kit: White Regular set Custom Tray and Acrylic Base Plate",
    description: "Fastray - Standard Kit: White Regular set Custom Tray and Acrylic Base Plate material: 1 Lb. Powder and 8 oz. Liquid. *HAZARDOUS MATERIALS",
    price: 87.68,
    image_url: "https://www.net32.com/cdn-cgi/image/dpr=2,,width=384,/media/shared/common/mp/bosworth/fastray/media/bosworth-fastray-custom-tray-material.jpg",
    category: "Materials",
    supplier: "Bosworth",
  },
]

export async function GET() {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 200))

  return NextResponse.json(products)
}

